export const companies = [
    {
      "RANK": 181, 
      "ciqId": 312932093, 
      "city": "Mountain View", 
      "cmCount": 17611, 
      "companyId": 1468009, 
      "country": 1080, 
      "countryName": "United States", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google LLC", 
      "secondaryName": null, 
      "state": "CA", 
      "stockExchangeAbbr": null, 
      "ticker": null,
      "website":"www.google.com",
    }, 
    {
      "RANK": 181, 
      "ciqId": 34899877, 
      "city": "London", 
      "cmCount": 59, 
      "companyId": 1325617, 
      "country": 1079, 
      "countryName": "United Kingdom", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google UK Limited", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 33313905, 
      "city": "Bengaluru", 
      "cmCount": 49, 
      "companyId": 1736001, 
      "country": 956, 
      "countryName": "India", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google India Pvt Ltd", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 246971938, 
      "city": "Mountain View", 
      "cmCount": 41, 
      "companyId": 3260403, 
      "country": 1080, 
      "countryName": "United States", 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Fiber Inc.", 
      "secondaryName": null, 
      "state": "CA", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 36335020, 
      "city": "Tokyo", 
      "cmCount": 38, 
      "companyId": 1512100, 
      "country": 962, 
      "countryName": "Japan", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Japan Inc.", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 26427657, 
      "city": "Dublin", 
      "cmCount": 32, 
      "companyId": 1226717, 
      "country": 958, 
      "countryName": "Ireland", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Ireland Limited", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "San Francisco", 
      "cmCount": 29, 
      "companyId": 3076954, 
      "country": 1080, 
      "countryName": null, 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 0, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Cloud", 
      "secondaryName": null, 
      "state": "CA  ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 146154696, 
      "city": "Singapore", 
      "cmCount": 23, 
      "companyId": 2109072, 
      "country": 1045, 
      "countryName": "Singapore", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Asia Pacific Pte. Ltd.", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "Mountain View", 
      "cmCount": 19, 
      "companyId": 3149805, 
      "country": 1080, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 0, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 1, 
      "parent__companyId": 7278853, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "GV", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google Ventures (GV)", 
      "secondaryName": null, 
      "state": "CA  ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 36334751, 
      "city": "Seoul", 
      "cmCount": 18, 
      "companyId": 1471229, 
      "country": 1052, 
      "countryName": "South Korea", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Korea, LLC.", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "Beijing", 
      "cmCount": 16, 
      "companyId": 1614432, 
      "country": 899, 
      "countryName": null, 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 0, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Beijing", 
      "secondaryName": null, 
      "state": "    ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": null, 
      "cmCount": 16, 
      "companyId": 3481138, 
      "country": null, 
      "countryName": null, 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 0, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Express", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 27551874, 
      "city": "Paris", 
      "cmCount": 13, 
      "companyId": 1329683, 
      "country": 930, 
      "countryName": "France", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google France SARL", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 36334947, 
      "city": "Hamburg", 
      "cmCount": 8, 
      "companyId": 1093863, 
      "country": 937, 
      "countryName": "Germany", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Germany GmbH", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "ZURICH", 
      "cmCount": 8, 
      "companyId": 1416347, 
      "country": 1061, 
      "countryName": "SWITZERLAND", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 0, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "GOOGLE SWITZERLAND GMBH", 
      "secondaryName": null, 
      "state": "ZH  ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 35932993, 
      "city": "Sydney", 
      "cmCount": 8, 
      "companyId": 1534647, 
      "country": 867, 
      "countryName": "Australia", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Australia Pty Limited", 
      "secondaryName": null, 
      "state": "NSW", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 36335960, 
      "city": "Stockholm", 
      "cmCount": 7, 
      "companyId": 1369102, 
      "country": 1060, 
      "countryName": "Sweden", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Sweden AB", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "SINGAPORE", 
      "cmCount": 7, 
      "companyId": 1585568, 
      "country": 1045, 
      "countryName": "SINGAPORE", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 0, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "GOOGLE SINGAPORE PTE. LTD.", 
      "secondaryName": null, 
      "state": "    ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "BEIJING", 
      "cmCount": 7, 
      "companyId": 1808374, 
      "country": 899, 
      "countryName": "CHINA", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 0, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "GOOGLE INFORMATION TECHNOLOGY (CHINA) CO.,LTD", 
      "secondaryName": null, 
      "state": "    ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": null, 
      "cmCount": 7, 
      "companyId": 3492644, 
      "country": 0, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 0, 
      "parent__city": null, 
      "parent__cmCount": 0, 
      "parent__companyId": null, 
      "parent__country": null, 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 0, 
      "parent__primaryName": null, 
      "parent__secondaryName": null, 
      "parent__state": null, 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google Summer of Code", 
      "secondaryName": null, 
      "state": "    ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 54497280, 
      "city": null, 
      "cmCount": 7, 
      "companyId": 7278861, 
      "country": null, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 1, 
      "parent__city": null, 
      "parent__cmCount": 0, 
      "parent__companyId": null, 
      "parent__country": null, 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 0, 
      "parent__primaryName": null, 
      "parent__secondaryName": null, 
      "parent__state": null, 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google Ventures", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 36334779, 
      "city": "M\u00e9xico", 
      "cmCount": 6, 
      "companyId": 1557571, 
      "country": 992, 
      "countryName": "Mexico", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Mexico S. de R.L. de C.V.", 
      "secondaryName": null, 
      "state": "DF", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "", 
      "cmCount": 6, 
      "companyId": 17083200, 
      "country": 0, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 0, 
      "parent__city": null, 
      "parent__cmCount": 0, 
      "parent__companyId": null, 
      "parent__country": null, 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 0, 
      "parent__primaryName": null, 
      "parent__secondaryName": null, 
      "parent__state": null, 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google Inc.", 
      "secondaryName": null, 
      "state": "    ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 36334800, 
      "city": "Amsterdam", 
      "cmCount": 5, 
      "companyId": 1418116, 
      "country": 1004, 
      "countryName": "Netherlands", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Netherlands B.V.", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 36334910, 
      "city": "Sao Paulo", 
      "cmCount": 5, 
      "companyId": 1889947, 
      "country": 884, 
      "countryName": "Brazil", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Brasil Internet Ltda.", 
      "secondaryName": null, 
      "state": "SP", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "", 
      "cmCount": 5, 
      "companyId": 15733340, 
      "country": 0, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 0, 
      "parent__city": null, 
      "parent__cmCount": 0, 
      "parent__companyId": null, 
      "parent__country": null, 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 0, 
      "parent__primaryName": null, 
      "parent__secondaryName": null, 
      "parent__state": null, 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google Launchpad", 
      "secondaryName": null, 
      "state": "    ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 36335000, 
      "city": "Milan", 
      "cmCount": 4, 
      "companyId": 1380470, 
      "country": 960, 
      "countryName": "Italy", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Italy s.r.l.", 
      "secondaryName": null, 
      "state": "MI", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 20000, 
      "ciqId": null, 
      "city": null, 
      "cmCount": 3, 
      "companyId": 18677643, 
      "country": null, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 0, 
      "parent__city": null, 
      "parent__cmCount": 0, 
      "parent__companyId": null, 
      "parent__country": null, 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 0, 
      "parent__primaryName": null, 
      "parent__secondaryName": null, 
      "parent__state": null, 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "CAUSEWAY BAY", 
      "cmCount": 3, 
      "companyId": 1490235, 
      "country": 953, 
      "countryName": "HONG KONG", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 0, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "GOOGLE (HONG KONG) LIMITED", 
      "secondaryName": null, 
      "state": "HK  ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "DUBLIN", 
      "cmCount": 3, 
      "companyId": 1589770, 
      "country": 958, 
      "countryName": "IRELAND", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 0, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "GOOGLE IRELAND HOLDINGS", 
      "secondaryName": null, 
      "state": "    ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "Moriarty", 
      "cmCount": 3, 
      "companyId": 3157389, 
      "country": 1080, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 0, 
      "parent__city": null, 
      "parent__cmCount": 0, 
      "parent__companyId": null, 
      "parent__country": null, 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 0, 
      "parent__primaryName": null, 
      "parent__secondaryName": null, 
      "parent__state": null, 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google / Titan Aerospace", 
      "secondaryName": null, 
      "state": "NM  ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 36335928, 
      "city": "Halifax", 
      "cmCount": 3, 
      "companyId": 3347003, 
      "country": 893, 
      "countryName": "Canada", 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Canada Corporation", 
      "secondaryName": null, 
      "state": "NS", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": null, 
      "cmCount": 3, 
      "companyId": 3377639, 
      "country": 0, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 0, 
      "parent__city": null, 
      "parent__cmCount": 0, 
      "parent__companyId": null, 
      "parent__country": null, 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 0, 
      "parent__primaryName": null, 
      "parent__secondaryName": null, 
      "parent__state": null, 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google Online Marketing Challenge", 
      "secondaryName": null, 
      "state": "    ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": "", 
      "cmCount": 3, 
      "companyId": 15962831, 
      "country": 0, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 0, 
      "parent__city": null, 
      "parent__cmCount": 0, 
      "parent__companyId": null, 
      "parent__country": null, 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 0, 
      "parent__primaryName": null, 
      "parent__secondaryName": null, 
      "parent__state": null, 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google Street View Trusted Partner", 
      "secondaryName": null, 
      "state": "    ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 53116571, 
      "city": null, 
      "cmCount": 2, 
      "companyId": 3157768, 
      "country": 1078, 
      "countryName": "United Arab Emirates", 
      "dncCode": 13973, 
      "dncCodeName": "Caveat", 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google FZ LLC", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 112761350, 
      "city": null, 
      "cmCount": 2, 
      "companyId": 3280134, 
      "country": 1080, 
      "countryName": "United States", 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Energy LLC", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": null, 
      "cmCount": 2, 
      "companyId": 3713379, 
      "country": 0, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 0, 
      "parent__city": null, 
      "parent__cmCount": 0, 
      "parent__companyId": null, 
      "parent__country": null, 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 0, 
      "parent__primaryName": null, 
      "parent__secondaryName": null, 
      "parent__state": null, 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google Teacher Academy", 
      "secondaryName": null, 
      "state": "    ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": null, 
      "cmCount": 2, 
      "companyId": 3736607, 
      "country": 899, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 1, 
      "parent__city": null, 
      "parent__cmCount": 0, 
      "parent__companyId": null, 
      "parent__country": null, 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 0, 
      "parent__primaryName": null, 
      "parent__secondaryName": null, 
      "parent__state": null, 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google Shanghai", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": "NASDAQ", 
      "ticker": "GOOAV"
    }, 
    {
      "RANK": 181, 
      "ciqId": null, 
      "city": null, 
      "cmCount": 2, 
      "companyId": 3755586, 
      "country": 0, 
      "countryName": null, 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 0, 
      "parent__city": null, 
      "parent__cmCount": 0, 
      "parent__companyId": null, 
      "parent__country": null, 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 0, 
      "parent__primaryName": null, 
      "parent__secondaryName": null, 
      "parent__state": null, 
      "parent__stockExchangeAbbr": null, 
      "parent__ticker": null, 
      "primaryName": "Google -> acquired Motorola Mobility -> acquired Netopia.com", 
      "secondaryName": null, 
      "state": "    ", 
      "stockExchangeAbbr": null, 
      "ticker": null
    }, 
    {
      "RANK": 181, 
      "ciqId": 36335195, 
      "city": "Singapore", 
      "cmCount": 2, 
      "companyId": 6852441, 
      "country": 1045, 
      "countryName": "Singapore", 
      "dncCode": null, 
      "dncCodeName": null, 
      "isConfirmed": 1, 
      "parent__city": "Mountain View", 
      "parent__cmCount": 445, 
      "parent__companyId": 3169493, 
      "parent__country": "United States", 
      "parent__dncCode": null, 
      "parent__dncCodeName": null, 
      "parent__isConfirmed": 1, 
      "parent__primaryName": "Alphabet Inc.", 
      "parent__secondaryName": null, 
      "parent__state": "CA", 
      "parent__stockExchangeAbbr": "NASDAQ", 
      "parent__ticker": "GOOG.L", 
      "primaryName": "Google Singapore Pte. Ltd.", 
      "secondaryName": null, 
      "state": null, 
      "stockExchangeAbbr": null, 
      "ticker": null
    }
  ];